# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('date_time', models.DateTimeField()),
                ('used_for', models.TextField()),
                ('type', models.CharField(blank=True, default='', max_length=20)),
                ('issues', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('access_token', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='devices',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DeviceManagementSystemApp.Students'),
        ),
    ]
