# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceManagementSystemApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='manager',
            field=models.BooleanField(default=False),
        ),
    ]
