# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceManagementSystemApp', '0004_students_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='property_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='devices',
            name='check_in_date_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
