# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceManagementSystemApp', '0006_auto_20160823_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='token',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
