# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceManagementSystemApp', '0007_auto_20160823_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='access_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
